services:
  db:
    image: postgres:15
    container_name: shopwise-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shopwise_db
      - POSTGRES_USER=reaksa_dev
      - POSTGRES_PASSWORD=postgre12345!!!
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: shopwise-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=shopwise_db
      - DB_USER=reaksa_dev
      - DB_PASSWORD=postgre12345!!!
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: